# Site settings
title: Bazlur's Blog Archive
description: A comprehensive archive of articles on Java, Software Development, and Technology
author:
  name: A N M Bazlur Rahman
  email: bazlur@jugbd.org
  url: https://bazlur.ca

# URL settings
url: "https://bazlur.com"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: none
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: none
  syntax_highlighter_opts:
    disable: true

# Theme - no theme (using custom layouts)
# Explicitly set no theme for GitHub Pages
theme: null

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "A N M Bazlur Rahman"
  - scope:
      path: ""
    values:
      image: "/assets/img/default-og.jpg"

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .jekyll-cache
  - .sass-cache
  - vendor
  - archive
  - vendor/bundle

# Include files
# include:
#   - _pages

# SEO settings
twitter:
  username: bazlur_rahman
  card: summary

social:
  name: A N M Bazlur Rahman
  links:
    - https://twitter.com/bazlur_rahman
    - https://github.com/rokon12
    - https://linkedin.com/in/bazlur

# Google Analytics (if you have one)
# google_analytics: UA-XXXXXXXXX-X

# Performance optimizations
sass:
  style: compressed
  
# HTML compression
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Asset optimization
assets:
  compression: true
  gzip: true