# Jekyll configuration for GitHub Pages
title: Bazlur's Blog Archive
description: A collection of articles on Java, Software Development, and Technology
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
show_downloads: false

# Directory settings
include: 
  - backup
  - backup/images

# Collections
collections:
  posts:
    output: true
    permalink: /:title/

# Default layout for markdown files
defaults:
  - scope:
      path: "backup"
      type: "pages"
    values:
      layout: "default"

# Navigation
header_pages:
  - about.md
  - categories.md

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-seo-tag
  - jekyll-sitemap

# Additional settings
relative_links:
  enabled: true
  collections: true

optional_front_matter:
  enabled: true

# Site settings
author:
  name: Bazlur Rahman
  email: bazlur@jugbd.org
  website: https://bazlur.ca

# Social media
social:
  twitter: bazlur_rahman
  github: rokon12
  linkedin: bazlur
