name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron:  '47 1 * * *'
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Pull latest changes
        run: |
          git config --global user.name 'Bazlur Rahman'
          git config --global user.email 'bazlur@jugbd.org'
          git pull origin main --rebase
      - name: Install Kotlin
        run: sudo snap install --classic --channel=1.7/stable kotlin
      - name: Update README
        run: ./update.main.kts
      - name: Commit README and push
        uses: EndBug/add-and-commit@v9
        with:
          add: README.md
          author_name: Bazlur Rahman
          author_email: bazlur@jugbd.org
          message: Automatically update README.md
          pull: '--rebase --autostash'
