name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron:  '47 1 * * *'
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install Kotlin
        run: sudo snap install --classic --channel=1.7/stable kotlin
      - name: Update README
        run: ./update.main.kts
      - name: Commit README and push
        uses: EndBug/add-and-commit@v9
        with:
          add: README.adoc
          default_author: github_actions
          message: Automatically update README.adoc
